# Generated by Django 4.1.3 on 2022-11-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(null=True)),
                ('gender', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('key', models.CharField(default=0, max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
        migrations.CreateModel(
            name='NewAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_name', models.CharField(max_length=50)),
                ('ag_email', models.EmailField(max_length=254, unique=True)),
                ('ag_logo', models.FileField(upload_to='agencydocs/')),
                ('ag_proof', models.FileField(upload_to='agencydocs/')),
                ('ag_password', models.CharField(max_length=50, unique=True)),
                ('ag_status', models.IntegerField(default=False)),
                ('keys', models.CharField(default=0, max_length=100)),
                ('crimetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.crimetype')),
            ],
        ),
    ]
