# Generated by Django 4.1.3 on 2022-11-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newagency',
            name='keys',
            field=models.BinaryField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='key',
            field=models.BinaryField(max_length=1000, null=True),
        ),
    ]
